# # 使用 Node.js v13 镜像作为基础
# FROM node:13

# # 设置工作目录
# WORKDIR /app

# # 复制 package.json 和 package-lock.json
# COPY package*.json ./

# # 安装依赖
# RUN npm install

# # 复制全部项目文件
# COPY . .

# # 对外暴露端口
# EXPOSE 3000

# # 启动 React 开发服务器
# CMD ["npm", "start"]

FROM node:13

WORKDIR /app

COPY package*.json ./
RUN npm install

# 热更新需要绑定监听地址
ENV HOST 0.0.0.0

EXPOSE 3000

CMD ["npm", "start"]